# https://dev.azure.com/home-assistant

parameters:
  builderVersion: ''
  builderApk: 'build-base'
  builderPip: 'Cython'
  builderArch: ['amd64', 'i386', 'armhf', 'armv7', 'aarch64']
  builderPath: ''
  builderEnvFile: false
  wheelsRequirement: ''
  wheelsRequirementDiff: ''
  wheelsPrebuildDir: ''
  wheelsSingle: false
  wheelsLocal: false
  preBuild: []
  jobName: 'Wheels'

jobs:
- job: '${{ parameters.jobName }}'
  timeoutInMinutes: 360
  strategy:
    matrix:
      ${{ each arch in parameters.builderArch }}:
        ${{ arch }}:
          buildArch: ${{ arch }}
          agentArch: 
  pool:
    name: BuildCluster
    demands:
    - Agent.OSArchitecture -equals $[ variables['agentArch'] ]
  variables:
  - group: wheels

  steps:
  - script: |
      mkdir -p .ssh
      echo -e "-----BEGIN RSA PRIVATE KEY-----\n$(wheelsSSH)\n-----END RSA PRIVATE KEY-----" >> .ssh/id_rsa
      ssh-keyscan -H $(wheelsHost) >> .ssh/known_hosts
      chmod 600 .ssh/*
    displayName: 'Install ssh key'
  - script: |
      sudo docker pull homeassistant/$(buildArch)-wheels:${{ parameters.builderVersion }}
    displayName: 'Install wheels builder'
  - ${{ parameters.preBuild }}
  - script: |
      build_args=()
      docker_args=()

      # Data Path
      if [ -n "${{ parameters.builderPath }}" ]; then
        data_path="$(pwd)/${{ parameters.builderPath }}"
      else
        data_path="$(pwd)"
      fi

      # Environment
      if [ "${{ parameters.builderEnvFile }}" == "true" ] && [ -f .env_file ]; then
        docker_args+=(--env-file .env_file)
      fi

      if [ -f "${{ parameters.wheelsRequirement }}" ]; then
        build_args+=(--requirement "${{ parameters.wheelsRequirement }}")
      fi

      if [ -f "${{ parameters.wheelsRequirementDiff }}" ]; then
        build_args+=(--requirement-diff "${{ parameters.wheelsRequirementDiff }}")
      fi

      if [ -d "${{ parameters.wheelsPrebuildDir }}" ]; then
        build_args+=(--prebuild-dir "${{ parameters.wheelsPrebuildDir }}")
      fi

      if [ "${{ parameters.wheelsSingle }}" == "true" ]; then
        build_args+=(--single)
      fi

      if [ "${{ parameters.wheelsLocal }}" == "true" ]; then
        build_args+=(--local)
      fi

      sudo docker run --rm \
        -v "$data_path:/data:ro" \
        -v "$(pwd)/.ssh:/root/.ssh:rw" \
        "${docker_args[@]}" \
        homeassistant/$(buildArch)-wheels:${{ parameters.builderVersion }} \
          --apk "${{ parameters.builderApk }}" \
          --pip "${{ parameters.builderPip }}" \
          --index $(wheelsIndex) \
          --upload rsync \
          --remote wheels@$(wheelsHost):/opt/wheels \
          "${build_args[@]}"
    displayName: 'Run wheels build'
