FROM buildpack-deps:18.04

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH
ENV DEBIAN_FRONTEND noninteractive

# http://bugs.python.org/issue19846
ENV LANG C.UTF-8

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup requirements
RUN \
	apt-get update && apt-get install -y --no-install-recommends \
		software-properties-common \
    && add-apt-repository ppa:jonathonf/ffmpeg-4
	&& apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        netbase \
        libudev-dev \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libswscale-dev \
        libswresample-dev \
        libavfilter-dev \
		gnupg2 \
	&& rm -rf /var/lib/apt/lists/*

ENV GPG_KEY 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
ENV PYTHON_VERSION 3.7.0

RUN set -ex \
	&& wget -O python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" \
	&& wget -O python.tar.xz.asc "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf" \
	&& gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEY" \
	&& gpg --batch --verify python.tar.xz.asc python.tar.xz \
	&& { command -v gpgconf > /dev/null && gpgconf --kill all || :; } \
	&& rm -rf "$GNUPGHOME" python.tar.xz.asc \
	&& mkdir -p /usr/src/python \
	&& tar -xJC /usr/src/python --strip-components=1 -f python.tar.xz \
	&& rm python.tar.xz \
	\
	&& cd /usr/src/python \
	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
	&& ./configure \
		--build="$gnuArch" \
		--enable-loadable-sqlite-extensions \
		--enable-optimizations \
		--enable-shared \
		--with-system-expat \
		--with-system-ffi \
		--without-ensurepip \
	&& make -j "$(nproc)" \
# setting PROFILE_TASK makes "--enable-optimizations" reasonable: https://bugs.python.org/issue36044
		PROFILE_TASK='-m test.regrtest --pgo \
            test_asyncio \
            test_asyncore \
            test_array \
            test_base64 \
            test_binascii \
            test_binop \
            test_bisect \
            test_bytes \
            test_cmath \
            test_codecs \
            test_collections \
            test_complex \
            test_dataclasses \
            test_datetime \
            test_decimal \
            test_difflib \
            test_embed \
            test_float \
            test_fstring \
            test_functools \
            test_generators \
            test_hashlib \
            test_heapq \
            test_int \
            test_itertools \
            test_json \
            test_long \
            test_math \
            test_memoryview \
            test_operator \
            test_ordered_dict \
            test_pickle \
            test_pprint \
            test_re \
            test_set \
			test_sqlite \
            test_statistics \
            test_struct \
            test_tabnanny \
            test_time \
            test_unicode \
            test_xml_etree \
            test_xml_etree_c \
		' \
	&& make install \
	&& ldconfig \
	\
	&& find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests \) \) \
			-o \
			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
		\) -exec rm -rf '{}' + \
	&& rm -rf /usr/src/python \
	\
	&& python3 --version

# make some useful symlinks that are expected to exist
RUN cd /usr/local/bin \
	&& ln -s idle3 idle \
	&& ln -s pydoc3 pydoc \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 20.0.2

RUN set -ex; \
	\
	wget -O get-pip.py "https://bootstrap.pypa.io/get-pip.py"; \
	\
	python get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		"pip==$PYTHON_PIP_VERSION" \
	; \
	pip --version; \
	\
	find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests \) \) \
			-o \
			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
		\) -exec rm -rf '{}' +; \
	rm -f get-pip.py

CMD ["python3"]
